Resources:
    fifoQueueOne:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: fifoQueueOne.fifo
        MessageRetentionPeriod: 120
        VisibilityTimeout: 10
        FifoQueue: true
        ContentBasedDeduplication: true
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - fifoQueueOne
              - Arn
          maxReceiveCount: 3
