service: test-serverless-sqs

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 10
  environment: ${file(serverless.ssm.yml)}
  apiGateway:
    apiKeys:
      - name : xApiKey
        value : ${file(./serverless.ssm.yml):X_API_KEY}

plugins:
  - serverless-offline-sqs
  - serverless-offline-ssm
  - serverless-offline


functions:
  senderSQS:
    handler: src/lambdas/senderSQS.handler
    name : Queue-SendMessage-Lambda
    description: to send sqs message
    events:
      - http:
          method: POST
          path: sender-queue
          private: true

  ReceiverSQS:
    handler: src/lambdas/receiverSQS.handler
    name: Queue-ReceiveMessage-Lambda
    description: to receive sqs message
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - fifoQueueOne
              - Arn
          batchSize: 10 
resources:
  - ${file(src/resources/api-gateway.yml)}
  - ${file(src/resources/sqs-config.yml)}

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
  serverless-offline-sqs:  
    sqsHost: 127.0.0.1
    sqsPort: 9324
    autoCreate: true
    apiVersion: "latest"
    endpoint: http://127.0.0.1:9324
    region: us-east-1
    accessKeyId: local
    secretAccessKey: local
    skipCacheInvalidation: false
  serverless-offline-ssm:
    stages:
      - dev
    ssm: 
      ${file(./serverless.ssm.yml)}

    
