service: test-serverless-sqs

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  memorySize: 512
  timeout: 10
  environment: ${file(serverless.env.yml)}

plugins:
  - serverless-offline-elasticmq
  - serverless-offline-sqs
  - serverless-offline-ssm
  - serverless-offline


functions:
  hello:
    handler: src/lambdas/hello.test
    events:
      - http:
          method: GET
          path: hello
          private: true
  senderSQS:
    handler: src/lambdas/senderSQS.compute
    events:
      - http:
          method: POST
          path: sender-queue
          private: true
  ReceiverSQS:
    handler: src/lambdas/receiverSQS.compute
    events:
      - sqs: arn:aws:sqs:region:XXXXXX:Receiver-Queue
resources:
  - ${file(src/resources/api-gateway.yml)}
  - ${file(src/resources/sqs-config.yml)}

custom:
  elasticmq:
    stages:
      - dev
    start:
      port: 9324
      noStart: false
  serverless-offline-sqs:
    autoCreate: true # create queue if not exists
    apiVersion: "2012-11-05"
    endpoint: http://0.0.0.0:9324
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
  serverless-offline-ssm:
    stages:
      - dev
    ssm:
      "/hello_test": "HELLO SSM"
      "/region": "eu-west-1"
      "/receiver_queue_url": "http://localhost:9324/queue/Receiver-Queue"
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
